# Typically, a Capstan pipeline would include a promote stage (see
# https://wiki.ithaka.org/pages/viewpage.action?spaceKey=softdel&title=The+container+image+promotion+process).
# However, since we are pulling an image from a remote repo, promotion:
# * does not work (the image is not located where the promotion job would look)
# * is not necessary (the deploy script will look at the remote repo before
#   looking through our snapshot/rc/stable repos).

include:
  - ".gitlab/deploy/_setup.yml"

stages:
  - prepare
  - check
  - promote
  - deploy
  - post-deploy
  - verify
  - notifications

# See Dockerfile. Note that the contents of the repository are _ignored by
# default_ and only built into the app when explicitly exempted in the
# .dockerignore. This is because the top-level repo contains lots of apparatus
# for test, CI, etc. that we don't actually need to deploy. In other words, if
# you have reached this comment because you're confused that your app builds
# fine locally with npm run build but isn't deploying properly, check the
# .dockerignore and consider whether you have recently added files or
# directories that you need to build.
build app image:
  stage: prepare
  extends: .build-image
  variables:
    CI_DEBUG_TRACE: true

# Local chart. This chart configures the database secrets.
render local chart:
  stage: prepare
  extends: .render-charts
  needs: []
  variables:
    HELM_CHART_PATH: $CI_PROJECT_DIR/k8s/chart
    # We have to explicitly set these here, where our environment variables are
    # available.
    # Why not set these in the file and reference env there? helm doesn't
    # interpolate environment variables. There are a few special environment
    # variables that capstan manually interpolates (see
    # https://gitlab.com/capstan/pow/gitlab-templates/-/blob/master/render-charts/src/config.js?ref_type=85391ddf3b421bacc53bcb9f2a23562ecf80e264
    # and
    # https://gitlab.com/capstan/pow/gitlab-templates/-/blob/master/render-charts/src/index.js?ref_type=https%3A%2F%2Fgitlab.com%2Fcapstan%2Fpow%2Fgitlab-templates%2F-%2Fblob%2Fmaster%2Frender-charts%2Fsrc%2Fconfig.js%3Fref_type%3D85391ddf3b421bacc53bcb9f2a23562ecf80e264#L21 ),
    # but we cannot freely set our own and expect that to work.
    EXTRA_HELM_TEMPLATE_OPTIONS: $DEFAULT_HELM_TEMPLATE_OPTIONS --set-string ssmParameter.JAIP_DB_URL=$JAIP_DB_URL --set autoscaling.enabled=$AUTOSCALING_ENABLED --set serviceAccountName=$SERVICE_ACCOUNT_NAME
  after_script:
    - ls -lah $MANIFEST_OUTPUT_DIRECTORY
    - mv $MANIFEST_OUTPUT_DIRECTORY/app-manifest.yml $MANIFEST_OUTPUT_DIRECTORY/app-manifest-extras.yml

# Default chart, configured via any `EXTRA_HELM_TEMPLATE_OPTIONS` referenced
# in `_setup.yml`. This chart deploys the app.
render capstan chart:
  stage: prepare
  extends: .render-charts
  needs: []

scan vulnerabilities:
  stage: check
  dependencies:
    - build app image
  extends: .vulnerability-scanner
  variables:
    SEVERITY: critical high unknown
    FAIL_ON_SEVERITY: critical high unknown
  before_script:
    # replace / with - in branch name to be friendly w/ job
    - export CI_COMMIT_BRANCH="${CI_COMMIT_BRANCH//\//-}"

lint:
  stage: check
  dependencies:
    - build app image
  image: $IMAGE_TAG
  tags:
    - test-runner
  before_script:
    - yarn install
  script: yarn lint:ci

unit tests:
  stage: check
  dependencies:
    - build app image
  image: $IMAGE_TAG
  variables:
    DB_MOCK: true
  tags:
    - test-runner
  before_script:
    - yarn install
  script: yarn test:ci

promote image:
  stage: promote
  extends: .promote-image

# There shouldn't be a need for this to be in a separate stage, but it consistently failed
# in the post-deploy stage and needed to be re-run.
wait for eureka:
  extends: .check-healthy-deployment
  stage: verify
