apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jaip-database-creds
  labels:
    ithaka/app: jaip-backend
    ithaka/app: {{ .Values.requiredTags.app }}
    ithaka/environment: {{ .Values.requiredTags.environment }}
    ithaka/owner: {{ .Values.requiredTags.owner }}
    ithaka/businessUnit: {{ .Values.requiredTags.businessUnit }}
spec:
  refreshInterval: 1h
  target:
    name: jaip-database-creds
  secretStoreRef:
    name: aws-ssm-secretstore
    kind: ClusterSecretStore
  data:
    - secretKey: JAIP_DB_URL
      remoteRef:
        # prettier-ignore
        key: {{ .Values.ssmParameter.JAIP_DB_URL }}
